<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="4" total="10" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="6832" started-at="2019-12-25T15:21:33Z" finished-at="2019-12-25T15:21:40Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="6832" started-at="2019-12-25T15:21:33Z" finished-at="2019-12-25T15:21:40Z">
      <class name="com.restassured.testcases.DeleteCustomerTest">
        <test-method status="FAIL" signature="deleteCustomer(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.DeleteCustomerTest@45018215]" name="deleteCustomer" duration-ms="1690" started-at="2019-12-25T15:21:38Z" data-provider="data" finished-at="2019-12-25T15:21:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{id=cus_GQMHWZZe2d27F3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[id is not present expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: id is not present expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.restassured.testcases.DeleteCustomerTest.deleteCustomer(DeleteCustomerTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCustomer -->
      </class> <!-- com.restassured.testcases.DeleteCustomerTest -->
      <class name="com.restassured.testcases.CreateCustomerTest">
        <test-method status="FAIL" signature="validateCreateCustomerAPIWithInvalidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@7219ec67]" name="validateCreateCustomerAPIWithInvalidSecretkey" duration-ms="3442" started-at="2019-12-25T15:21:33Z" data-provider="data" finished-at="2019-12-25T15:21:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=sood07deepak@abc.com, name=Deepak Sood, description=This is description}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [401]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [401]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at com.restassured.testcases.CreateCustomerTest.validateCreateCustomerAPIWithInvalidSecretkey(CreateCustomerTest.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:71)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithInvalidSecretkey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@7219ec67]" name="validateCreateCustomerAPIWithValidSecretkey" duration-ms="1611" started-at="2019-12-25T15:21:36Z" data-provider="data" finished-at="2019-12-25T15:21:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=sood07deepak@abc.com, name=Deepak, description=This is description}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretkey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@7219ec67]" name="validateCreateCustomerAPIWithValidSecretkey" duration-ms="1633" started-at="2019-12-25T15:21:36Z" data-provider="data" finished-at="2019-12-25T15:21:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=abc@abc.com, name=Rahul, description=Description 3}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretkey -->
        <test-method status="PASS" signature="validateCreateCustomerAPIWithValidSecretkey(java.util.Hashtable)[pri:0, instance:com.restassured.testcases.CreateCustomerTest@7219ec67]" name="validateCreateCustomerAPIWithValidSecretkey" duration-ms="1637" started-at="2019-12-25T15:21:36Z" data-provider="data" finished-at="2019-12-25T15:21:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{email=abc@abc.com, name=Champ, description=Description}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateCreateCustomerAPIWithValidSecretkey -->
      </class> <!-- com.restassured.testcases.CreateCustomerTest -->
      <class name="com.restassured.rough.Testparameterization">
        <test-method status="FAIL" signature="testData(java.util.Hashtable)[pri:0, instance:com.restassured.rough.Testparameterization@7b227d8d]" name="testData" duration-ms="0" started-at="2019-12-25T15:21:38Z" finished-at="2019-12-25T15:21:38Z">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Cannot inject @Test annotated Method [testData] with [class java.util.Hashtable].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Cannot inject @Test annotated Method [testData] with [class java.util.Hashtable].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:407)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:356)
at org.testng.internal.Parameters.createParameters(Parameters.java:635)
at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
      </class> <!-- com.restassured.rough.Testparameterization -->
      <class name="com.restassured.setup.BaseTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.restassured.setup.BaseTest@4c1d9d4b]" name="setUp" is-config="true" duration-ms="559" started-at="2019-12-25T15:21:32Z" finished-at="2019-12-25T15:21:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.restassured.setup.BaseTest@4c1d9d4b]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-12-25T15:21:40Z" finished-at="2019-12-25T15:21:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.restassured.setup.BaseTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
